name: nest
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda
  - python>=3.9
  - R>=4.2
  - r-devtools
  - r-ggpubr
  - r-rcppeigen
  - r-rspectra
  - r-reticulate
  - r-circlize
  - r-rtsne
  - r-biocmanager
  - bioconductor-biobase
  - bioconductor-complexheatmap
  - bioconductor-biocneighbors
  - bioconductor-bayesspace
  - rpy2
  - anndata2ri
  - numba<0.56
  - matplotlib<3.7
  - pandas<2
  - seaborn
  - scikit-learn
  - python-igraph
  - leidenalg
  - ipython
  - jupyterlab
  - numpy
  - scipy
  - scanpy=1.8.2
  - pillow
  - tqdm
  - networkx<3.0
  - statsmodels
  - squidpy
  - mygene
  - shapely
  - goatools
  - colorcet
  - pip